name: Issues Report
about: Report issues with XConomy
body:
  - type: input
    attributes:
      placeholder: What version of XConomy do you use?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issues
      placeholder: 'Describe your issues'
    validations:
      required: true