#设置
Settings:
  #Chinese ChineseTW English French Spanish Russian Turkish Japanese German
  language: Chinese
  #是否检查新版本
  check-update: true
  #是否使用Mysql
  mysql: false
  #TOP10和服务器总金额刷新时间间隔 (单位秒)
  refresh-time: 300
  #如果设置为true,XConomy将会注册以下指令
    # - economy
    # - eco
    # - ebalancetop
    # - ebaltop
    # - eeconomy
  #如果你服务器上有安装Essentials插件
  #XConomy将会覆盖这些指令
  eco-command: true
  #XConomy将会禁用Essentials插件的经济功能
  #仅仅是经济功能.
  disable-essentials: true
  #初始余额
  initial-bal: 0
  #非玩家账户是否启用,可以解决某些插件无法创建非玩家账户问题,比如Factions,Towny
  #非玩家账户的数据不会进行BC同步
  non-player-account: false
  #缓存纠正是否开启
  #如果需要经常对数据库的数据进行修改，建议开启
  #需要注意的是，缓存纠正不会二次验证金额的数值大小在存扣款过程中
  #非玩家账户的数据不支持此功能
  cache-correction: false
  #是否保存转账记录
  #只支持MySQL
  transaction-record: true
  #如果你的服务器为半正版模式，请设置为 true
  #半正版模式既不是正版模式，也不是离线模式
  #半正版模式无法完美兼容在 BungeeCord 发送转账提醒的功能
  #该功能不支持 Sponge 服务器
  semi-online-mode: false
  #无视玩家名称的大小写
  username-ignore-case: false


#货币的显示
Currency:
  singular-name: dollar
  plural-name: dollars
  #余额是否为整数
  integer-bal: false
  thousands-separator: ','
  display-format: '%balance% %currencyname%'
  #最大金额（默认值为最大值）
  max-number: '10000000000000000'


#SQLite设置
SQLite:
  #地址为文件夹路径
  path: Default


#MySQL设置
MySQL:
  host: localhost:3306
  user: root
  pass: root
  database: data
  #自动添加 "_", 可以使用 %sign% 来表示服务器ID (见BungeeCord设置)
  table-suffix: ''
  encoding: utf8
  timezone: ''


#连接池设置
Pool-Settings:
  #是否使用连接池
  usepool: false
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 180000
  idle-timeout: 60000


#BungeeCord设置
BungeeCord:
  #是否启用BC同步
  #BC同步开启后,控制台和其他插件将无法在服务器无人的情况下修改金额
  #需要在spigot.yml中设置bungeecord为true
  enable: false
  #服务器标识,请保持需要同步的子服务器的标识和数据库的设置一致
  sign: aa